//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpBBQLibary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kochvorgang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kochvorgang()
        {
            this.Bilder = new HashSet<Bilder>();
        }
    
        public int Id { get; set; }
        public string Protokoll { get; set; }
        public int RezeptId { get; set; }
        public int KochId { get; set; }
    
        public virtual Rezept Rezept { get; set; }
        public virtual Koch Koch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilder> Bilder { get; set; }
    }
}
