//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBQLibary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Koch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Koch()
        {
            this.Kochvorgang = new HashSet<Kochvorgang>();
        }
    
        public int Id { get; set; }
        public string Nutzerkennung { get; set; }
        public string Equipment { get; set; }
        public string Zutaten { get; set; }
        public string Holz { get; set; }
        public string Bewertung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kochvorgang> Kochvorgang { get; set; }
    }
}
