//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    
    public partial class BilderSet
    {
        public int Id { get; set; }
        public string Bildernamen { get; set; }
        public string Bilderart { get; set; }
        public string ImagePath { get; set; }
    }
}
